### ISSUE TITLE
acc-provision -d shouldn't require -a

### ISSUE THREAD

**Issue by ceridwen** [noironetworks/aci-containers#16]
At the moment you get an unclear error if you use -d without -a, but -d should just work without -a.

**Comment by readams** [comment]
commit 935cc29f659d6ca8fa23211ae70bef78c47122a7
Author: Rob Adams <readams@readams.net>
Date:   Tue Nov 21 14:12:27 2017 -0800

    Make -d not require -a to be specified
    
    Signed-off-by: Rob Adams <readams@readams.net>
