### ISSUE TITLE
1.11 support through pip install acc-provision

### ISSUE THREAD

**Issue by headconnect** [noironetworks/aci-containers#166]
Hi,

Version 1.9.5 of acc-provision is the latest on pip, and only supports k8s 1.10. Is there any timeline or guidance on when a new release supporting 1.11 (and possibly experimental 1.12 etc) will be made available?

**Comment by snaiksat** [comment]
The latest release (Nov 2nd) does support 1.11. 1.12 is currently being tested and should be available soon.

**Comment by headconnect** [comment]
Sounds good, thanks. Would be nice if you tagged releases through github as well as pushing to pip :)
