### ISSUE TITLE
acc-provision crashes after using -d twice

### ISSUE THREAD

**Issue by ceridwen** [noironetworks/aci-containers#17]
It should provide a sensible error rather than a Python stack trace.

**Comment by readams** [comment]
commit bc83532d29f558499dc65221033c80eff3d081c4
Author: Rob Adams <readams@readams.net>
Date:   Tue Nov 21 14:13:01 2017 -0800

    Don't fail with an exception if already unprovisioned
    
    Signed-off-by: Rob Adams <readams@readams.net>
