### ISSUE TITLE
[Kubernetes] If 'aci_config:vrf:tenant' is different from 'aci_config:system_id', faults appear in the created BDs

### ISSUE THREAD

**Issue by JoseIgnacioTamayo** [noironetworks/aci-containers#173]
Hi,

Regarding the Kubernetes integration:

If, following some guidelines found on Cisco doc (https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/kb/b_Kubernetes_Integration_with_ACI.pdf) I would like to have the L3out and VRF in a Tenant 'KubernetesInfra-Tn', the acc-provisioning tool will still create another tenant with name '{{aci_config:system_id}}', will put the EPGs there, but not properly link the BDs to the VRF in tenant {{aci_config:vrf:tenant}}. This creates a fault in the BDs

I just forked, in a few days I could propose the changes and some improved comments in the doc to indicate that there is a Tenant created per aci_config:system_id (per Kubernetes Cluster) while they will all respect the binding to the indicated VRF in aci_config:vrf:tenant

**Comment by JoseIgnacioTamayo** [comment]
I am sorry, totally my bad. By checking the created objects, I realized that effectively the BDs can only be associated to a VRF in the same tenant  '{{aci_config:system_id}}' or 'common'.

However, I guess it is better to quit early the provisioning if the pre-existant elements are not present. And a check that the value {{aci_config:vrf:tenant} is either of the two valid ones.

**Comment by snaiksat** [comment]
This implementation has been revamped.
