### ISSUE TITLE
The external subnet option in the input file doesn't do anything on OpenShift

### ISSUE THREAD

**Issue by ceridwen** [noironetworks/aci-containers#20]
OpenShift uses 172.29.0.0/16 as its default subnet for external service IPs, see [Assigning Unique External IPs for Ingress Traffic](https://docs.openshift.com/container-platform/3.6/admin_guide/tcp_ingress_external_ports.html).  There apparently is a configuration option, `ingressIPNetworkCIDR` in the `/etc/origin/master/master-config.yaml` that can change this, but acc_provision doesn't currently use it.

**Comment by readams** [comment]
This is expected for OpenShift as it allocates external IPs and there seems to be nothing that can be done about it.  In OpenShift, we're setting an option in ACI containers controller that disables the allocation of load balancer IPs.
