### ISSUE TITLE
urllib3 not a part of requests anymore

### ISSUE THREAD

**Issue by camrossi** [noironetworks/aci-containers#27]
As per:
https://stackoverflow.com/questions/27981545/suppress-insecurerequestwarning-unverified-https-request-is-being-made-in-pytho/28002687#28002687

This code in apic_provision.py is broken and indeed is not working anymore on my recent centos VM:
```
import requests
requests.packages.urllib3.disable_warnings()
```

It should be replaced with:
```
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

```

**Comment by readams** [comment]
You've presumably manually installed a newer version than exists on centos using pip.  Even ubuntu 17.04 still has 2.18.1.  The suggested change won't work though since it would fail on the older version.  In the meantime don't use pip and install from our packages.  Would have to see if there's a way to work for both.

**Comment by camrossi** [comment]
Thanks Rob, I think the OPenShift ansible installer changed something on my system. 
It worked the first time installed it Github but as today it stopped working. both Pip and github source.

**Comment by readams** [comment]
If you're running the

**Comment by readams** [comment]
Use the packages we ship not pip or github.

**Comment by readams** [comment]
commit f24738df527299ab328c6c50a034af80b6939166 (origin/urllib3-disable-warnings)
Author: Rob Adams <readams@readams.net>
Date:   Wed Nov 22 10:24:41 2017 -0800

    Change how we disable insecure request warnings
    
    * The existing code apparently causes problems with very new requests
      library, and the "newer" way seems OK on RHEL7 and Ubuntu
      16.04 and 17.10 at least
    
    Signed-off-by: Rob Adams <readams@readams.net>
