### ISSUE TITLE
latest build 1.7.0 supporting k8s versions 1.7 and 1.8 ?

### ISSUE THREAD

**Issue by nohir0** [noironetworks/aci-containers#33]
is the acc_provision 1.7.0 release now supporting kubernetes 1.7 and/or 1.8 ?

This is the only documentation about the integration I could find so far:
https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/kb/b_Kubernetes_Integration_with_ACI.html

Are there any release notes and more comprehensive installation/configuration documentation available? Above documentation leaves some questions unanswered...

Thanks

**Comment by readams** [comment]
Release 1.7 will support Kubernetes 1.7, and 1.8 will support Kubernetes 1.8.  Are you trying to do a deployment of Kubernetes at the moment?  If that doc doesn't provide enough info, Cisco support can help with the deployment and getting any questions answered on your specific needs.
