### ISSUE TITLE
ACI CNI plugin

### ISSUE THREAD

**Issue by aleksandrbog** [noironetworks/aci-containers#467]
We have deployed Openshift cluster with Cisco cni plugin. Our cluster has aproximately 600 pods and 20 nodes. Plugin works fine, but when we make changes in network configuration - change snat policy or increase subnet size - leaf start blocking connections from pods(10.205.0.1/16) to node(10.56.196.1/24). Restart aci-containers-host-**** pod on node fix the problem.
Logs from leaf and plugin from one node 
[aci-containers-controller-snat-operator.zip](https://github.com/noironetworks/aci-containers/files/4403350/aci-containers-controller-snat-operator.zip)

[aci-containers-controller.log](https://github.com/noironetworks/aci-containers/files/4403329/aci-containers-controller.log)
[aci-containers-host.log](https://github.com/noironetworks/aci-containers/files/4403331/aci-containers-host.log)
[aci-containers-openvswitch.log](https://github.com/noironetworks/aci-containers/files/4403332/aci-containers-openvswitch.log)
[mcast-daemon.log](https://github.com/noironetworks/aci-containers/files/4403333/mcast-daemon.log)
[opflex-agent.log](https://github.com/noironetworks/aci-containers/files/4403334/opflex-agent.log)
[10.56.196.28.txt](https://github.com/noironetworks/aci-containers/files/4403337/10.56.196.28.txt)

**Comment by snaiksat** [comment]
The SNAT implementation was revamped in the 5.0.1 release, closing this issue for now, please let us know if you see it again.
